spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: "create" # 실행 시점에 모든 디비 지우고 다시 생성
    properties:
      hibernate:
#        show_sql: true # 쿼리를 출력하는 옵션 sout 에 출력
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug # SQL 쿼리를 로그로 출력









