spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create # 실행 시점에 모든 디비 지우고 다시 생성
    properties:
      hibernate:
        #show_sql: true
        default_batch_fetch_size: 1000 # (최적화) 어차피 다 가져올 것이므로 한계 개수인 1000개 설정함
        format_sql: true
    open-in-view: true # true 가 기본값(JPA 영속성 컨텍스트 엔드 시점까지 살아있을, false 시 레포지토리 까지 살아있음)

logging:
  level:
    org.hibernate.SQL: debug # SQL 쿼리를 로그로 출력
#    org.hibernate.type: trace # 타입을 로그로 출력 쿼리에 들어간 파라미터를 출력


server:
  port: 8080
  error:
    include-binding-errors: always











